crimera/revanced-integrations

CHANGELOG.md, app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/Utils.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsActivity.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java, gradle.properties
update(Twitter): refactor mod settings
feat(Twitter): Added `Hide For You` in Mod Settings
=> Mod Settings Updates

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsActivity.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java
feat(Twitter): Added Hide Promoted Trends to Mod Settings
feat(Twitter): Added Hide Community Notes to mod settings
=> More Mod Settings

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/Utils.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsActivity.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java
update(Twitter): Added `Reader Mode Patch` in mod settings
update(Twitter): Added `Undo Post Patch` in mod settings
feat(Twitter): Added `App Icon and NavBar Customisation` settings
=> More Premium Features to Mod Settings

app/src/main/java/app/revanced/integrations/twitter/patches/TimelineEntry.java, app/src/main/java/app/revanced/integrations/twitter/patches/links/UnshortenUrlsPatch.java, stub/src/main/java/com/twitter/model/json/core/JsonUrlEntity.java, stub/src/main/java/com/twitter/model/json/timeline/urt/JsonTimelineEntry.java
*	update(Twitter): Added Stubs for Timeline entry Hook
*	update(Twitter): Added Stubs for `No shortened URL` patch
=> Added Stubs

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/Utils.java, app/src/main/java/app/revanced/integrations/twitter/patches/FeatureSwitchPatch.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsActivity.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java
feat(Twitter): Added `Feature Flag Hook`
update(Twitter): Made some patches to use flags
feat(Twitter): Added `Hide immersive player` patch
=> Feature Flag Hook

app/src/main/java/app/revanced/integrations/shared/Utils.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsActivity.java
=> Added resource file for strings

app/src/main/java/app/revanced/integrations/shared/settings/preference/SharedPrefCategory.java, app/src/main/java/app/revanced/integrations/twitter/Utils.java, app/src/main/java/app/revanced/integrations/twitter/settings/BackupPrefActivity.java, app/src/main/java/app/revanced/integrations/twitter/settings/RestorePrefActivity.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsActivity.java, app/src/main/java/app/revanced/integrations/twitter/settings/featureflags/FeatureFlagsFragment.java
=> feat(Twitter): Added ability to export and import prefs & feature flags

app/src/main/java/app/revanced/integrations/twitter/patches/links/OpenLinksWithAppChooserPatch.java
=> fix: don't use chooser for internal stuff

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java
fix [issue #136](https://github.com/crimera/piko/issues/136)
=> feat(Twitter): Added `Customize timeline top bar` patch

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/patches/TweetInfo.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java, stub/src/main/java/com/twitter/api/model/json/core/JsonApiTweet.java
refactor(Twitter): refactor `Hide community notes` patch
feat(Twitter): Add `Force translate` patch
feat(Twitter): Add `Hide promote button` patch
=> add(Twitter): Added `TweetInfoHook`

app/src/main/java/app/revanced/integrations/shared/Utils.java, app/src/main/java/app/revanced/integrations/twitter/patches/DownloadPatch.java
* refactor(Twitter): Vertical download pref dialog
* feat(Twitter): Added share link in `Add ability to copy media link` patch
=> refactor `Add ability to copy media link` patch

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/patches/customise/ProfileTabs.java, app/src/main/java/app/revanced/integrations/twitter/patches/customise/SideBar.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsAboutFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java
and also
refactor(Twitter): Refactor about fragment logic
=> feat(Twitter): Added Customize side bar items patch

app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsAboutFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java
~ refactor(Twitter): Separated `App icon` and `Navigation icon` patch
~ refactor(Twitter): Sorted about fragment
=> refactor(Twitter): Separated `App icon` and `Navigation icon` patch

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/patches/TimelineEntry.java, app/src/main/java/app/revanced/integrations/twitter/patches/links/UnshortenUrlsPatch.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsFragment.java, stub/src/main/java/com/twitter/model/json/card/JsonBindingValue.java, stub/src/main/java/com/twitter/model/json/card/JsonCardInstanceData.java
~ refactor(Twitter): Added `No shortened URL` as a settings toggle
~ refactor(Twitter): Renamed patch `Remove Buy Premium Banner` to `Remove message prompts Banner`
! fix(Twitter): Fix `Customize profile tabs` crash after `10.43`
=> Refactors and fixes

app/src/main/java/app/revanced/integrations/twitter/patches/DatabasePatch.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsAboutFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java, stub/src/main/java/com/twitter/util/user/UserIdentifier.java
feat(Twitter): Added `Delete from database` patch
=> feat(Twitter): Added `Delete from database` patch

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/Utils.java, app/src/main/java/app/revanced/integrations/twitter/patches/NativeDownloader.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsAboutFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java
~ refactor(Twitter): Optimise `Native downloader`
* feat(Twitter): Added `Control video auto scroll` patch
* feat(Twitter): Added `Enable PiP mode automatically` patch
~ refactor(Twitter): Strings refactor
* feat(Twitter): Added `Remove premium upsell` patch
=> Some more features

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/patches/TimelineEntry.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsAboutFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java
+ feat(Twitter): Added `Remove main event` patch
~ refactor(Twitter): Separated/Added `Remove superhero event` patch
=> Some explore features

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/patches/TimelineEntry.java, app/src/main/java/app/revanced/integrations/twitter/settings/PikoSettingsButton.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsAboutFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java, stub/src/main/java/com/twitter/model/json/timeline/urt/JsonTimelineModuleItem.java
* refactor(Twitter): Added quick settings button in side drawer
* feat(Twitter): Added Remove `videos for you` patch
=> Quick settings and remove `videos for you` patch

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsAboutFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java
* feat(Twitter): Added `Customize reply sort filter` patch
* feat(Twitter): Added Remember filter for `Customize reply sort filter`
=> Features related to sorting replies

app/src/main/java/app/revanced/integrations/twitter/settings/SettingsFragment.java
* update(Twitter): Added hide 'Settings and privacy' in `Customize sidebar items`
* fix(Twitter): Fix hide 'Premium' in `Customize side bar items`
=> Customize sidebar updates

app/src/main/java/app/revanced/integrations/twitter/settings/ActivityHook.java, app/src/main/java/app/revanced/integrations/twitter/settings/DeepLink.java, app/src/main/java/app/revanced/integrations/twitter/settings/featureflags/FeatureFlagsFragment.java
Add flags using the following deep link pattern:
**_https://x.com/i/addflags?f=<flag_name>&v=<flag_value>_**
_"flag_name"_ should be of type String
_"flag_value"_ can be true/false or 1/0
=> feat(Twitter): Add flags via deep links

app/src/main/java/app/revanced/integrations/twitter/Utils.java, app/src/main/java/app/revanced/integrations/twitter/patches/DatabasePatch.java, app/src/main/java/app/revanced/integrations/twitter/settings/ScreenBuilder.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/widgets/ButtonPref.java
* fix(Twitter): Fix dialog positive button string
* refactor(Twitter): refactor custom app icon and nav icons
=> refactor(Twitter): refactor custom app icon and nav icons

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/patches/TimelineEntry.java, app/src/main/java/app/revanced/integrations/twitter/settings/ScreenBuilder.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java, stub/src/main/java/com/twitter/model/json/core/JsonSensitiveMediaWarning.java
* refactor(Twitter): Added toggle for `Show sensitive media patch`
* fix(Twitter): fix `hide Google ads`
=> refactor `Show sensitive media patch` and fix `hide Google ads`

app/src/main/java/app/revanced/integrations/twitter/Utils.java, app/src/main/java/app/revanced/integrations/twitter/settings/ScreenBuilder.java
* refactor(Twitter): Change Customize Navbar string in/from 10.70
* fix(Twitter): app icon & customize navbar url opening in browser
=> fix(Twitter): app icon & customise navbar url opening in browser

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/patches/TimelineEntry.java, app/src/main/java/app/revanced/integrations/twitter/patches/customise/Customise.java, app/src/main/java/app/revanced/integrations/twitter/settings/ScreenBuilder.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java, app/src/main/java/app/revanced/integrations/twitter/settings/fragments/SettingsAboutFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/widgets/MultiSelectListPref.java, stub/src/main/java/com/twitter/model/json/search/JsonTypeaheadResponse.java
*	feat(Twitter): Added `Remove top people in search` patch
*	feat(Twitter): Added `Customize search suggestions` patch
* 	feat(Twitter): Added `Customize search tab items` patch
*	refactor(Twitter): Added empty check for choices during Customisation
*	refactor(Twitter): Strings in 'About'
=> feat(Twitter): Explore search features

app/src/main/java/app/revanced/integrations/twitter/Pref.java, app/src/main/java/app/revanced/integrations/twitter/patches/NativeDownloader.java, app/src/main/java/app/revanced/integrations/twitter/settings/DeepLink.java, app/src/main/java/app/revanced/integrations/twitter/settings/ScreenBuilder.java, app/src/main/java/app/revanced/integrations/twitter/settings/Settings.java, app/src/main/java/app/revanced/integrations/twitter/settings/SettingsStatus.java, app/src/main/java/app/revanced/integrations/twitter/settings/fragments/PageFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/fragments/SettingsAboutFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/fragments/SettingsFragment.java, app/src/main/java/app/revanced/integrations/twitter/settings/widgets/ListPref.java
* refactor(Twitter): Added 'Native features' section
* refactor(Twitter): Added native download filename customization
=> refactor(Twitter): Native features

app/src/main/java/app/revanced/integrations/twitter/patches/links/HandleCustomDeepLinksPatch.java
Dependency for https://github.com/crimera/piko/pull/626
=> feat(Twitter): support custom deeplink hosts
